name = "find_tool"
description = "Simple find tool based on rejuvenation library"
version = "0.0.0"

authors = ["Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]

executables = ["find_tool"]

[[depends-on]]
libadalang = "^22.0.0"
rejuvenation = "*"

[[pins]]
rejuvenation = { path = ".." } 

